"""ArenaOS database schema. Owned by the integrator — builders do not edit this file.

Modules needing extra tables create `arenaos/db/ext_<module>.py` exposing
`register(engine)` which calls `Base.metadata.create_all(engine, tables=[...])`
for only their own tables.
"""
from __future__ import annotations

from datetime import datetime, timezone

from sqlalchemy import (
    JSON,
    Boolean,
    Column,
    DateTime,
    ForeignKey,
    Integer,
    LargeBinary,
    String,
    Text,
    UniqueConstraint,
    create_engine,
)
from sqlalchemy.orm import backref, declarative_base, relationship

Base = declarative_base()


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True)
    email = Column(String(320), unique=True, nullable=False)
    password_hash = Column(String(512), nullable=False)
    role = Column(String(32), default="operator", nullable=False)
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=utcnow, nullable=False)
    updated_at = Column(DateTime, default=utcnow, onupdate=utcnow, nullable=False)


class ApiKey(Base):
    __tablename__ = "api_keys"

    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    name = Column(String(128), nullable=False)
    key_hash = Column(String(128), unique=True, nullable=False)
    scopes = Column(JSON, default=list, nullable=False)
    created_at = Column(DateTime, default=utcnow, nullable=False)
    last_used_at = Column(DateTime, nullable=True)


class Project(Base):
    __tablename__ = "projects"

    id = Column(String(32), primary_key=True)
    name = Column(String(255), nullable=False)
    slug = Column(String(255), unique=True, nullable=False)
    description = Column(Text, default="", nullable=False)
    workspace_path = Column(String(1024), default="", nullable=False)
    git_url = Column(String(1024), default="", nullable=False)
    status = Column(String(32), default="active", nullable=False)
    created_at = Column(DateTime, default=utcnow, nullable=False)
    updated_at = Column(DateTime, default=utcnow, onupdate=utcnow, nullable=False)


class Conversation(Base):
    __tablename__ = "conversations"

    id = Column(String(32), primary_key=True)
    project_id = Column(String(32), ForeignKey("projects.id"), nullable=True)
    title = Column(String(512), default="New conversation", nullable=False)
    mode = Column(String(32), default="chat", nullable=False)
    created_at = Column(DateTime, default=utcnow, nullable=False)
    updated_at = Column(DateTime, default=utcnow, onupdate=utcnow, nullable=False)
    messages = relationship("Message", back_populates="conversation", order_by="Message.created_at")


class Message(Base):
    __tablename__ = "messages"

    id = Column(Integer, primary_key=True)
    conversation_id = Column(String(32), ForeignKey("conversations.id"), nullable=False)
    role = Column(String(16), nullable=False)  # user | assistant | system | tool
    content = Column(Text, default="", nullable=False)
    model = Column(String(128), default="", nullable=False)
    task_id = Column(String(32), nullable=True)
    tokens_in = Column(Integer, nullable=True)
    tokens_out = Column(Integer, nullable=True)
    created_at = Column(DateTime, default=utcnow, nullable=False)
    conversation = relationship("Conversation", back_populates="messages")


class Task(Base):
    __tablename__ = "tasks"

    id = Column(String(32), primary_key=True)
    project_id = Column(String(32), ForeignKey("projects.id"), nullable=True)
    parent_id = Column(String(32), ForeignKey("tasks.id"), nullable=True)
    goal = Column(Text, nullable=False)
    task_type = Column(String(32), default="general", nullable=False)
    mode = Column(String(32), default="autonomous", nullable=False)
    model = Column(String(128), default="", nullable=False)
    status = Column(String(32), default="created", nullable=False)
    plan = Column(JSON, nullable=True)
    checkpoint = Column(JSON, nullable=True)
    result = Column(Text, default="", nullable=False)
    error = Column(Text, default="", nullable=False)
    attempts = Column(Integer, default=0, nullable=False)
    max_retries = Column(Integer, default=3, nullable=False)
    priority = Column(Integer, default=0, nullable=False)
    created_at = Column(DateTime, default=utcnow, nullable=False)
    updated_at = Column(DateTime, default=utcnow, onupdate=utcnow, nullable=False)
    started_at = Column(DateTime, nullable=True)
    finished_at = Column(DateTime, nullable=True)
    events = relationship("TaskEvent", order_by="TaskEvent.seq")
    children = relationship("Task", backref=backref("parent", remote_side=[id]))


class TaskEvent(Base):
    __tablename__ = "task_events"
    __table_args__ = (UniqueConstraint("task_id", "seq", name="uq_task_event_seq"),)

    id = Column(Integer, primary_key=True)
    task_id = Column(String(32), ForeignKey("tasks.id"), nullable=False)
    seq = Column(Integer, nullable=False)
    kind = Column(String(32), nullable=False)  # plan|step_start|tool_call|step_result|error|debug|done
    data = Column(JSON, nullable=False)
    created_at = Column(DateTime, default=utcnow, nullable=False)


class Memory(Base):
    __tablename__ = "memories"

    id = Column(Integer, primary_key=True)
    layer = Column(String(16), nullable=False)  # short | long | project
    project_id = Column(String(32), ForeignKey("projects.id"), nullable=True)
    key = Column(String(255), default="", nullable=False)
    content = Column(Text, nullable=False)
    tags = Column(JSON, default=list, nullable=False)
    source = Column(String(64), default="user", nullable=False)
    created_at = Column(DateTime, default=utcnow, nullable=False)
    updated_at = Column(DateTime, default=utcnow, onupdate=utcnow, nullable=False)


class ToolCall(Base):
    __tablename__ = "tool_calls"

    id = Column(Integer, primary_key=True)
    task_id = Column(String(32), nullable=True)
    conversation_id = Column(String(32), nullable=True)
    tool = Column(String(64), nullable=False)
    args = Column(JSON, nullable=False)  # redacted before storing
    result_summary = Column(Text, default="", nullable=False)
    ok = Column(Boolean, nullable=False)
    duration_ms = Column(Integer, nullable=True)
    permission = Column(String(32), default="", nullable=False)
    model = Column(String(128), default="", nullable=False)
    created_at = Column(DateTime, default=utcnow, nullable=False)


class Plugin(Base):
    __tablename__ = "plugins"

    id = Column(Integer, primary_key=True)
    name = Column(String(128), unique=True, nullable=False)
    version = Column(String(32), default="0.0.0", nullable=False)
    manifest = Column(JSON, nullable=False)
    status = Column(String(16), default="installed", nullable=False)  # installed|disabled|error
    permissions = Column(JSON, default=list, nullable=False)
    created_at = Column(DateTime, default=utcnow, nullable=False)
    updated_at = Column(DateTime, default=utcnow, onupdate=utcnow, nullable=False)


class Credential(Base):
    __tablename__ = "credentials"

    id = Column(Integer, primary_key=True)
    name = Column(String(128), unique=True, nullable=False)
    kind = Column(String(32), nullable=False)  # api_key | token | password | env
    encrypted_value = Column(LargeBinary, nullable=False)  # Fernet ciphertext
    meta = Column(JSON, default=dict, nullable=False)
    created_at = Column(DateTime, default=utcnow, nullable=False)
    updated_at = Column(DateTime, default=utcnow, onupdate=utcnow, nullable=False)


class AuditLog(Base):
    __tablename__ = "audit_log"

    id = Column(Integer, primary_key=True)
    actor = Column(String(128), default="agent", nullable=False)
    action = Column(String(64), nullable=False)
    resource = Column(String(255), default="", nullable=False)
    detail = Column(JSON, default=dict, nullable=False)  # redacted
    created_at = Column(DateTime, default=utcnow, nullable=False)


class Execution(Base):
    __tablename__ = "executions"

    id = Column(Integer, primary_key=True)
    task_id = Column(String(32), nullable=True)
    tool_call_id = Column(Integer, nullable=True)
    workspace = Column(String(1024), nullable=False)
    command = Column(Text, nullable=False)
    exit_code = Column(Integer, nullable=True)
    stdout_path = Column(String(1024), default="", nullable=False)
    stderr_path = Column(String(1024), default="", nullable=False)
    duration_ms = Column(Integer, nullable=True)
    created_at = Column(DateTime, default=utcnow, nullable=False)


class Setting(Base):
    __tablename__ = "settings"

    key = Column(String(128), primary_key=True)
    value = Column(JSON, nullable=False)
    updated_at = Column(DateTime, default=utcnow, onupdate=utcnow, nullable=False)


class Notification(Base):
    __tablename__ = "notifications"

    id = Column(Integer, primary_key=True)
    channel = Column(String(32), nullable=False)  # in_app | telegram | webhook | email
    target = Column(String(255), default="", nullable=False)
    subject = Column(String(512), default="", nullable=False)
    body = Column(Text, default="", nullable=False)
    status = Column(String(16), default="pending", nullable=False)  # pending|sent|failed
    error = Column(Text, default="", nullable=False)
    created_at = Column(DateTime, default=utcnow, nullable=False)


class DeployService(Base):
    __tablename__ = "deploy_services"

    id = Column(Integer, primary_key=True)
    project_id = Column(String(32), nullable=True)
    provider = Column(String(32), default="render", nullable=False)
    remote_id = Column(String(128), default="", nullable=False)
    name = Column(String(128), nullable=False)
    service_type = Column(String(32), default="web", nullable=False)  # web|worker|cron|static
    url = Column(String(1024), default="", nullable=False)
    status = Column(String(32), default="unknown", nullable=False)
    blueprint = Column(JSON, default=dict, nullable=False)
    last_synced_at = Column(DateTime, nullable=True)


class ScheduledJob(Base):
    __tablename__ = "scheduled_jobs"

    id = Column(Integer, primary_key=True)
    name = Column(String(255), unique=True, nullable=False)
    kind = Column(String(16), default="cron", nullable=False)  # cron | once
    schedule = Column(String(255), nullable=False)  # cron expr or ISO datetime
    timezone = Column(String(64), default="UTC", nullable=False)
    task_spec = Column(JSON, nullable=False)
    enabled = Column(Boolean, default=True, nullable=False)
    last_run_at = Column(DateTime, nullable=True)
    next_run_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=utcnow, nullable=False)
    updated_at = Column(DateTime, default=utcnow, onupdate=utcnow, nullable=False)


class PermissionGrantRecord(Base):
    __tablename__ = "permission_grants"

    id = Column(Integer, primary_key=True)
    permission = Column(String(64), nullable=False)
    scope = Column(String(64), nullable=False)  # once | task:<id> | session | always | deny
    resource = Column(String(255), default="", nullable=False)
    created_at = Column(DateTime, default=utcnow, nullable=False)
    expires_at = Column(DateTime, nullable=True)


def init_db(engine=None) -> None:
    """Create all core tables plus any registered extension tables."""
    from arenaos.core.config import get_settings

    engine = engine or create_engine(get_settings().resolved_db_url(), future=True)
    Base.metadata.create_all(engine)
    # Extension tables (db/ext_*.py) register themselves on import of arenaos.db.ext_*.
    import importlib
    import pkgutil

    import arenaos.db as db_pkg

    for module_info in pkgutil.iter_modules(db_pkg.__path__):
        if module_info.name.startswith("ext_"):
            module = importlib.import_module(f"arenaos.db.{module_info.name}")
            register = getattr(module, "register", None)
            if register:
                register(engine)
